import { useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore } from 'react'
import { createPortal } from 'react-dom'
import type { CSSProperties,FormEvent } from 'react'
import { emptyPreferenceValues,type PreferenceValues,type PreferenceCard } from '../../shared/agent-context'
import type { ContextTier } from '../../shared/agent-contracts'
import { auth } from '../auth'
import { Ic,Spinner } from '../SketchIcon'
import { AgentController,type AgentUiState } from './controller'
import { AGENT_CONTEXT_EVENT,goFromAgent } from './navigation'
import { activeCompact,JOB_LABELS,phoneDevice,shouldSend,validAnime,viewportPlacement,fallbackChoices,type AnimeContext } from './model'
import { MessageCard } from './AgentCards'
import './agent.css'

// 550×500 图集只展示顶部正面头像（x=180, y=0, 190×190），不新增位图。
export function AgentAvatar():JSX.Element{return <span className="agent-avatar" aria-hidden="true"/>}
type Section='chat'|'history'|'preferences'|'context'|'manage'
function readViewport(){
  const viewport=window.visualViewport,width=viewport?.width??window.innerWidth,height=viewport?.height??window.innerHeight,top=viewport?.offsetTop??0
  const tabs=document.querySelector<HTMLElement>('.m-tabs'),rect=tabs?.getBoundingClientRect()
  // 平板沿用站内底部导航；浮层避开可见导航，不给主页面额外腾位置。
  const bottomInset=tabs&&rect&&getComputedStyle(tabs).display!=='none'&&rect.bottom>=top+height-2&&rect.top<top+height?Math.max(0,top+height-Math.max(top,rect.top)):0
  return{...viewportPlacement({width,height:height-bottomInset,left:viewport?.offsetLeft??0,top}),phone:phoneDevice(window.matchMedia('(pointer: coarse)').matches,window.screen.width,window.screen.height)}
}
function useViewport(){
  const [value,setValue]=useState(readViewport)
  useLayoutEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>setValue(readViewport()))};const viewport=window.visualViewport,mq=window.matchMedia('(pointer: coarse)');window.addEventListener('resize',update);viewport?.addEventListener('resize',update);viewport?.addEventListener('scroll',update);mq.addEventListener('change',update);update();return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',update);viewport?.removeEventListener('resize',update);viewport?.removeEventListener('scroll',update);mq.removeEventListener('change',update)}},[])
  return value
}
export function AgentHost({userId,enabled,onLogin}:{userId:number|null|undefined;enabled:boolean;onLogin:()=>void}):JSX.Element|null{
  const viewport=useViewport(),[open,setOpen]=useState(false),[context,setContext]=useState<{owner:number|null;anime:AnimeContext;seq:number}|null>(null)
  const trigger=useRef<HTMLElement|null>(null),launcher=useRef<HTMLButtonElement>(null),pendingLogin=useRef(false)
  useEffect(()=>{document.documentElement.dataset.agentDevice=viewport.phone?'phone':'wide';return()=>{delete document.documentElement.dataset.agentDevice}},[viewport.phone])
  useEffect(()=>{const receive=(event:Event)=>{const value=(event as CustomEvent<unknown>).detail;if(!validAnime(value)||viewport.phone||!enabled)return;trigger.current=document.activeElement as HTMLElement;setContext({owner:userId??null,anime:value,seq:Date.now()});setOpen(true)};window.addEventListener(AGENT_CONTEXT_EVENT,receive);return()=>window.removeEventListener(AGENT_CONTEXT_EVENT,receive)},[userId,enabled,viewport.phone])
  useEffect(()=>{if(pendingLogin.current&&userId){pendingLogin.current=false;setContext(previous=>previous?.owner===null?{...previous,owner:userId}:previous);setOpen(true)}},[userId])
  const close=()=>{setOpen(false);queueMicrotask(()=>{const target=trigger.current?.isConnected?trigger.current:launcher.current;target?.focus({preventScroll:true})})}
  const login=()=>{pendingLogin.current=true;setOpen(false);onLogin()}
  if(!enabled||userId===undefined||viewport.phone)return null
  const style={'--agent-left':`${viewport.left}px`,'--agent-top':`${viewport.top}px`,'--agent-width':`${viewport.width}px`,'--agent-height':`${viewport.height}px`,'--agent-launch-left':`${viewport.launcherLeft}px`,'--agent-launch-top':`${viewport.launcherTop}px`} as CSSProperties
  return createPortal(<div className="agent-layer" data-short={viewport.short} data-open={open} style={style}>
    {userId?<OwnedAgent key={userId} uid={userId} open={open} close={close} login={login} anime={context?.owner===userId?context:null} launcher={launcher} toggle={()=>{if(!open)trigger.current=document.activeElement as HTMLElement;setOpen(!open)}}/>:<><Launcher open={open} toggle={()=>{trigger.current=document.activeElement as HTMLElement;setOpen(!open)}} launcher={launcher}/>{open&&<section id="agent-window" className="agent-window" role="dialog" aria-modal="false" aria-labelledby="agent-title" onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();close()}}}><PanelHeader close={close}/><div className="agent-guest"><AgentAvatar/><h3>纱雾助手</h3><button type="button" className="btn btn-primary" onClick={login} autoFocus>登录 / 注册</button></div></section>}</>}
  </div>,document.body)
}
function OwnedAgent(props:{uid:number;open:boolean;close:()=>void;login:()=>void;anime:{anime:AnimeContext;seq:number}|null;launcher:React.RefObject<HTMLButtonElement>;toggle:()=>void}):JSX.Element{
  const [controller,setController]=useState<AgentController|null>(null)
  useEffect(()=>{let storage:Storage|undefined;try{storage=window.sessionStorage}catch{}const instance=new AgentController(props.uid,__AGENT_CLIENT_RELEASE__,{remember:storage,onAuthExpired:()=>{void auth.refresh()}});setController(instance);return()=>instance.dispose()},[props.uid])
  return controller?<ConnectedAgent {...props} controller={controller}/>:<Launcher open={props.open} toggle={props.toggle} launcher={props.launcher}/>
}
function Launcher({open,toggle,launcher,state}:{open:boolean;toggle:()=>void;launcher:React.RefObject<HTMLButtonElement>;state?:AgentUiState}):JSX.Element{
  const running=state?.watchingRun?.state==='running'||activeCompact(state?.job??null),pending=state?.messages.some(m=>m.actions.some(a=>a.state==='prepared'))
  return <button ref={launcher} type="button" className={`agent-launcher${running?' is-running':''}`} onClick={toggle} aria-haspopup="dialog" aria-expanded={open} aria-controls="agent-window" aria-label={open?'收起纱雾助手':'打开纱雾助手'}><AgentAvatar/>{(running||pending)&&<i className="agent-activity" aria-label={running?'运行中':'有待确认操作'}/>}{Boolean(state?.unread)&&<b className="agent-unread" aria-label={`${state!.unread} 条未读`}>{state!.unread}</b>}</button>
}
function PanelHeader({close,section='chat'}:{close:()=>void;section?:Section}):JSX.Element{
  const title={chat:'纱雾助手',history:'历史对话',preferences:'偏好',context:'上下文',manage:'对话设置'}[section]
  return <header className="agent-header"><span className="agent-header-mark">✦</span><div><h2 id="agent-title">{title}</h2></div><button type="button" className="agent-icon" onClick={close} aria-label="收起手帐" title="收起手帐"><Ic name="minus" cls="ic"/></button></header>
}
function ConnectedAgent({controller:c,open,close,login,anime,launcher,toggle}:{controller:AgentController;open:boolean;close:()=>void;login:()=>void;anime:{anime:AnimeContext;seq:number}|null;launcher:React.RefObject<HTMLButtonElement>;toggle:()=>void}):JSX.Element{
  const appliedAnime=useRef<number|null>(null)
  const state=useSyncExternalStore(c.subscribe,c.getSnapshot),[section,setSection]=useState<Section>('chat'),input=useRef<HTMLTextAreaElement>(null),scroll=useRef<HTMLDivElement>(null),bottom=useRef(true),composing=useRef(false),[newBelow,setNewBelow]=useState(false),[refreshConfirm,setRefreshConfirm]=useState(false)
  useEffect(()=>{void c.initialize()},[c])
  useEffect(()=>{c.setOpen(open);if(open&&section==='chat')requestAnimationFrame(()=>input.current?.focus({preventScroll:true}))},[c,open,section])
  useEffect(()=>{if(anime&&state.ready&&!state.loading&&!state.busy&&!state.syncing&&appliedAnime.current!==anime.seq){appliedAnime.current=anime.seq;setSection('chat');void c.setAnime(anime.anime)}},[c,anime,state.ready,state.loading,state.busy,state.syncing])
  useEffect(()=>{const on=()=>{if(document.visibilityState==='visible')void c.refresh()};window.addEventListener('focus',on);document.addEventListener('visibilitychange',on);return()=>{window.removeEventListener('focus',on);document.removeEventListener('visibilitychange',on)}},[c])
  useLayoutEffect(()=>{if(!open||section!=='chat')return;const node=scroll.current;if(!node)return;if(bottom.current){node.scrollTop=node.scrollHeight;setNewBelow(false)}else setNewBelow(true)},[open,section,state.messages])
  const running=state.watchingRun?.state==='running',compacting=activeCompact(state.job),locked=Boolean(state.busy)||state.syncing||running||compacting||Boolean(state.session?.archivedAt)||state.loading
  const changeSection=(next:Section)=>{setSection(next);if(next==='preferences')void c.preferences();if(next==='history')void c.list()}
  const normalStatus=state.syncing?'同步中…':state.loading?'加载中…':state.busy?`${state.busy}…`:compacting?JOB_LABELS[state.job!.stage]:state.status||''
  const stale=state.knowledge?.release!==c.clientVersion&&state.knowledge?.status==='ready'
  const fallback=fallbackChoices(state.draft||state.messages.filter(m=>m.role==='user').at(-1)?.body||'',state.anime)
  const go=(kind:ReturnType<typeof fallbackChoices>[number])=>{close();if(kind==='search')goFromAgent({kind:'search'},c.uid);else if(state.anime)goFromAgent(kind==='review'?{kind:'review',bgmId:state.anime.bgmId}:{kind:'source',bgmId:state.anime.bgmId,source:kind},c.uid)}
  return <><Launcher open={open} toggle={toggle} launcher={launcher} state={state}/>{open&&<section id="agent-window" className="agent-window" role="dialog" aria-modal="false" aria-labelledby="agent-title" onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();close()}}}>
    <div className="agent-top"><PanelHeader close={close} section={section}/><nav className="agent-nav" aria-label="助手功能"><button type="button" aria-current={section==='chat'?'page':undefined} onClick={()=>changeSection('chat')}>对话</button><button type="button" disabled={Boolean(state.busy)||state.loading||state.syncing} onClick={()=>changeSection('history')}><Ic name="tracks" cls="ic ic-sm"/>历史对话</button><button type="button" disabled={Boolean(state.busy)||state.loading||state.syncing} onClick={()=>{setSection('chat');void c.newSession()}}><Ic name="plus" cls="ic ic-sm"/>新对话</button><button type="button" onClick={()=>changeSection('preferences')}><Ic name="heart" cls="ic ic-sm"/>偏好</button><button type="button" onClick={()=>changeSection('manage')} aria-label="对话设置" aria-current={section==='manage'?'page':undefined}><Ic name="dots" cls="ic ic-sm"/></button></nav>
    {state.anime&&<div className="agent-anime-chip"><Ic name="clip" cls="ic ic-sm"/><span title={state.anime.title}>{state.anime.title}</span><small>#{state.anime.bgmId}</small><button type="button" className="agent-icon" disabled={locked} onClick={()=>void c.setAnime(null)} aria-label="移除当前番剧"><Ic name="x" cls="ic ic-sm"/></button></div>}</div>
    <div hidden={!state.error&&!normalStatus} className={`agent-feedback ${state.error?'is-error':''}`} role="status" aria-live="polite"><span title={state.error?.message??normalStatus}>{state.error?.message??normalStatus}</span>{state.error?<button type="button" disabled={Boolean(state.busy)||state.syncing} onClick={()=>void(section==='preferences'?c.preferences():c.refresh())}>重新读取</button>:state.loading||state.busy?<Spinner size={14}/>:null}</div>
    {state.watchingRun?.state==='running'&&state.watchingRun.sessionId!==state.session?.id&&<div className="agent-update"><span>另一段对话正在运行。</span><button type="button" disabled={Boolean(state.busy)||state.syncing} onClick={()=>void c.select(state.watchingRun!.sessionId)}>查看对话</button></div>}
    {stale&&<div className="agent-update"><span>页面有新版了。</span><button type="button" onClick={()=>{if(state.draft){setRefreshConfirm(true);return}window.location.reload()}}>刷新页面</button></div>}
    {stale&&refreshConfirm&&<div className="agent-confirm" role="alertdialog" aria-label="刷新确认"><p>刷新会清除未发送的草稿，确认刷新？</p><div><button type="button" className="btn btn-sm" onClick={()=>setRefreshConfirm(false)}>取消</button><button type="button" className="btn btn-sm" onClick={()=>window.location.reload()}>确认刷新</button></div></div>}
    {section==='chat'?<div className="agent-chat-wrap"><div className="agent-chat agent-scroll" ref={scroll} role="log" aria-label="对话记录" aria-live="polite" onScroll={()=>{const node=scroll.current;if(node){bottom.current=node.scrollHeight-node.scrollTop-node.clientHeight<48;if(bottom.current)setNewBelow(false)}}}>
      {state.beforeSeq!==null&&<button className="agent-older" type="button" disabled={Boolean(state.busy)||state.syncing} onClick={()=>{bottom.current=false;void c.older()}}>翻前面的记录</button>}
      {!state.messages.length&&!state.loading&&<div className="agent-empty"><div className="agent-empty-art"><AgentAvatar/><span>紗霧</span></div><h3>{state.anime?'就从这部番聊起吧。':'今天，想聊哪部番？'}</h3><div className="agent-suggestions">{[state.anime?'这部适合什么人看？先别剧透':'想找一部轻松的短番','我最近在追哪些番？','本周有哪些番更新？'].map(question=><button type="button" key={question} onClick={()=>{c.setDraft(question);input.current?.focus()}}>{question}<span>↗</span></button>)}</div></div>}
      {state.messages.map(message=><MessageCard key={message.id} message={message} onPin={()=>void c.pin(message)} disabled={locked}/>)}
      {state.run?.state==='paused'&&<div className="agent-inline-status"><p>回复已暂停</p><button type="button" className="btn btn-sm" disabled={!state.run.canResume||Boolean(state.busy)||running||compacting} onClick={()=>void c.resume()}>继续回复</button></div>}
      {(state.run?.state==='failed'||state.run?.state==='cancelled')&&<div className="agent-inline-status"><p>已保留生成内容</p><button type="button" className="btn btn-sm" onClick={()=>{c.retryDraft();input.current?.focus()}}>重新编辑问题</button></div>}
      {(state.error||state.run?.state==='failed'||state.messages.at(-1)?.toolSummaries.some(tool=>tool.status!=='ok'))&&fallback.length>0&&<div className="agent-fallbacks">{fallback.map(kind=><button type="button" key={kind} onClick={()=>go(kind)}>{({search:'打开普通搜索',review:'打开点评助手',xifan:'去稀饭搜索',girigiri:'去 Girigiri 搜索'})[kind]} <Ic name="external" cls="ic ic-sm"/></button>)}</div>}
    </div>{newBelow&&<button type="button" className="agent-new-below" onClick={()=>{bottom.current=true;scroll.current?.scrollTo({top:scroll.current.scrollHeight});setNewBelow(false)}}>有新内容 ↓</button>}</div>
    :section==='history'?<HistoryPane c={c} state={state} onSelect={()=>setSection('chat')}/>
    :section==='preferences'?<PreferencesPane c={c} state={state}/>
    :section==='context'?<ContextPane c={c} state={state} locked={locked}/>
    :<ManagePane key={state.session?.id??'new'} c={c} state={state} onDone={()=>setSection('chat')}/>}
    {section==='chat'&&<form className="agent-composer" onSubmit={(event:FormEvent)=>{event.preventDefault();bottom.current=true;void c.send()}}><textarea ref={input} className="agent-scroll" value={state.draft} placeholder={state.session?.archivedAt?'此对话已归档':'输入消息…'} aria-label="给纱雾的消息" rows={2} maxLength={32_000} disabled={Boolean(state.session?.archivedAt)||state.authExpired} onChange={event=>c.setDraft(event.target.value)} onCompositionStart={()=>{composing.current=true}} onCompositionEnd={()=>{composing.current=false}} onKeyDown={event=>{if(shouldSend(event.key,event.shiftKey,event.nativeEvent.isComposing||composing.current,event.keyCode)){event.preventDefault();if(!locked){bottom.current=true;void c.send()}}}}/><div className="agent-composer-foot"><button type="button" className="agent-context-control" onClick={()=>changeSection('context')} disabled={!state.session}><Ic name="clip" cls="ic ic-sm"/>上下文</button><small>{state.draft.length>30_000?`${state.draft.length}/32000`:'Enter 发送 · Shift + Enter 换行'}</small>{running?<button type="button" className="agent-send is-stop" disabled={Boolean(state.busy)||state.syncing} onClick={()=>void c.cancel()} aria-label="停止回复"><Ic name="pause" cls="ic ic-sm"/></button>:compacting?<button type="button" className="agent-send is-stop" disabled={Boolean(state.busy)||state.syncing} onClick={()=>void c.cancelCompact()} aria-label="停止整理"><Ic name="pause" cls="ic ic-sm"/></button>:<button type="submit" className="agent-send" aria-label="发送消息" title={state.knowledge?.conditions.answerModelReady?'发送消息':'回答模型尚未接入'} disabled={!state.draft.trim()||locked||state.knowledge?.status!=='ready'||(!state.knowledge?.conditions.answerModelReady&&!(state.draft.trim()==='/compact'&&state.knowledge.conditions.contextModelReady))}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M12 18V6M6 12l6-6 6 6"/></svg></button>}</div></form>}
    {state.authExpired&&<div className="agent-expired"><p>登录状态更新了，重新登录再接着聊吧。</p><button type="button" className="btn btn-primary" onClick={login}>去登录</button><button type="button" className="agent-text-button" onClick={()=>window.location.reload()}>刷新页面</button></div>}
  </section>}</>
}
function HistoryPane({c,state,onSelect}:{c:AgentController;state:AgentUiState;onSelect:()=>void}):JSX.Element{
  return <div className="agent-pane agent-scroll"><div className="agent-segments"><button type="button" className={!state.archived?'on':''} onClick={()=>void c.list(false)}>最近对话</button><button type="button" className={state.archived?'on':''} onClick={()=>void c.list(true)}>已归档</button></div>{!state.sessions.length&&<p className="agent-pane-hint">暂无历史对话</p>}{state.sessions.map(session=><div key={session.id} className={`agent-session-row ${session.id===state.session?.id?'is-current':''}`}><button type="button" className="agent-session-open" disabled={Boolean(state.busy)||state.syncing} onClick={()=>{void c.select(session.id);onSelect()}}><Ic name="tracks"/><span><b>{session.title}</b><small>{session.messageCount} 条记录 · {new Date(session.updatedAt).toLocaleDateString()}</small></span></button><button type="button" className="agent-text-button agent-session-archive" aria-label={`${session.archivedAt?'恢复':'归档'}：${session.title}`} disabled={Boolean(state.busy)||state.syncing||session.id===state.watchingRun?.sessionId&&state.watchingRun.state==='running'} onClick={()=>void c.archiveSession(session)}>{session.archivedAt?'恢复':'归档'}</button></div>)}{state.cursor&&<button type="button" className="agent-older" onClick={()=>void c.list(state.archived,true)}>加载更多</button>}</div>
}
export const PREFERENCE_EXAMPLES:Record<PreferenceCard['category'],string>={tone:'例如：回答简短直接，避免剧透',liked_tags:'例如：日常、喜剧、治愈',avoided_tags:'例如：恐怖、血腥',recommendation_focus:'例如：优先推荐已完结、12 集以内的番'}
const CATEGORIES:Record<PreferenceCard['category'],string>={tone:'说话方式',liked_tags:'喜欢的标签',avoided_tags:'避开的类型',recommendation_focus:'推荐重点'}
function PreferencesPane({c,state}:{c:AgentController;state:AgentUiState}):JSX.Element{
  const [category,setCategory]=useState<PreferenceCard['category']>('tone'),[values,setValues]=useState<PreferenceValues>(()=>({...state.preferenceSettings?.values??emptyPreferenceValues()}))
  useEffect(()=>{if(state.preferenceSettings)setValues({...state.preferenceSettings.values})},[state.preferenceSettings?.version])
  const settings=state.preferenceSettings,locked=!settings||Boolean(state.busy)||state.syncing
  const changed=Boolean(settings)&&Object.keys(values).some(key=>values[key as keyof PreferenceValues].trim()!==settings!.values[key as keyof PreferenceValues])
  return <div className="agent-pane agent-scroll"><form className="agent-pref-form" onSubmit={event=>{event.preventDefault();if(settings)void c.savePreferences(values,settings.version)}}><div className="agent-category" role="tablist" aria-label="偏好分类">{Object.entries(CATEGORIES).map(([key,label])=><button key={key} type="button" role="tab" aria-selected={category===key} className={category===key?'on':''} onClick={()=>setCategory(key as PreferenceCard['category'])}>{label}</button>)}</div><textarea className="agent-scroll" aria-label={CATEGORIES[category]} value={values[category]} disabled={locked} onChange={event=>setValues({...values,[category]:event.target.value})} maxLength={500} rows={3} placeholder={`${PREFERENCE_EXAMPLES[category]}（留空使用默认）`}/><button type="submit" className="btn btn-sm btn-primary" disabled={locked||!changed}>保存</button></form></div>
}
function ContextPane({c,state,locked}:{c:AgentController;state:AgentUiState;locked:boolean}):JSX.Element{
  return <div className="agent-pane agent-scroll"><p className="agent-pane-hint">压缩上下文不删除聊天记录。</p><div className="agent-context-box"><b>{activeCompact(state.job)?JOB_LABELS[state.job!.stage]:state.context?.active?`已整理到摘要 v${state.context.active.summary_version}`:'暂无摘要'}</b><button type="button" className="btn btn-sm btn-primary" disabled={!state.session||locked||!state.knowledge?.conditions.contextModelReady} onClick={()=>void c.compact()}>压缩上下文</button></div><h3 className="agent-small-heading">上下文容量</h3><div className="agent-category">{(['64k','128k','256k','1m'] as ContextTier[]).map(tier=><button type="button" key={tier} disabled={locked} className={state.session?.contextTier===tier?'on':''} onClick={()=>void c.tier(tier,false)}>{tier}</button>)}</div><label className="agent-checkbox"><input type="checkbox" checked={state.context?.adaptive??true} disabled={locked} onChange={event=>void c.tier(state.session?.contextTier??'128k',event.target.checked)}/>自动调整容量</label>{state.context?.active&&<div className="agent-summary"><small>当前摘要</small><p>{state.context.active.state.task_goal.value}</p>{state.context.active.state.next_step.value&&<p>接下来：{state.context.active.state.next_step.value}</p>}</div>}<h3 className="agent-small-heading">之前的版本</h3>{!state.context?.versions.length&&<p className="agent-pane-hint">暂无摘要版本</p>}{state.context?.versions.map(version=><div className="agent-version" key={version.summary_version}><span>v{version.summary_version}<small>{new Date(version.createdAt).toLocaleString()}</small></span><button type="button" className="agent-text-button" disabled={locked||version.summary_version===state.context?.active?.summary_version} onClick={()=>void c.restore(version.summary_version)}>{version.summary_version===state.context?.active?.summary_version?'正在使用':'恢复这版'}</button></div>)}</div>
}
function ManagePane({c,state,onDone}:{c:AgentController;state:AgentUiState;onDone:()=>void}):JSX.Element{
  const [title,setTitle]=useState(state.session?.title??''),[titleDirty,setTitleDirty]=useState(false),[confirm,setConfirm]=useState<'clear'|'delete'|null>(null)
  const locked=Boolean(state.busy)||state.syncing||state.watchingRun?.state==='running'||activeCompact(state.job)
  useEffect(()=>{if(!titleDirty)setTitle(state.session?.title??'')},[state.session?.title,titleDirty])
  return <div className="agent-pane agent-scroll"><label className="agent-field">对话名称<input aria-label="对话名称" placeholder="新对话" value={title} maxLength={100} disabled={!state.session||locked} onChange={event=>{setTitle(event.target.value);setTitleDirty(true)}}/></label><button type="button" className="btn btn-sm btn-primary" disabled={!state.session||!title.trim()||locked} onClick={()=>void c.manage('rename',title.trim()).then(success=>{if(success)setTitleDirty(false)})}>保存名称</button><div className="agent-manage-actions">{Boolean(state.session?.startedAt)&&<button type="button" disabled={!state.session||locked} onClick={()=>void c.manage('archive')}>{state.session?.archivedAt?'恢复对话':'归档对话'}</button>}<button type="button" disabled={!state.session||Boolean(state.busy)} onClick={()=>void c.export().then(data=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='agent-history.json';link.hidden=true;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)})}>导出聊天记录</button><button type="button" disabled={!state.session||locked} onClick={()=>setConfirm('clear')}>清空本次会话</button><button type="button" disabled={!state.session||locked} onClick={()=>setConfirm('delete')}>删除对话</button></div>{confirm&&<div className="agent-confirm" role="alertdialog" aria-modal="false" aria-label="确认操作"><p>{confirm==='clear'?'清空全部聊天记录？对话名称保留。':'删除此对话及全部聊天记录？'}</p><div><button type="button" className="btn btn-sm" onClick={()=>setConfirm(null)}>取消</button><button type="button" className="btn btn-sm btn-danger" disabled={locked} onClick={()=>{void c.manage(confirm).then(success=>{if(success&&!c.getSnapshot().error){setConfirm(null);onDone()}})}}>确认{confirm==='clear'?'清空':'删除'}</button></div></div>}</div>
}
