import { useEffect,useRef,useState } from 'react'

interface ProviderStatus {enabled:boolean;disabled?:boolean;canPrepare?:boolean;ready:boolean;source:'server'|'byok';model:string;endpoint?:string;profiles:{endpoint:string;model:string;contextTokens:number}[];usage:{tokens:number;cost:number;turns:number;warningCost:number}}
export function ProviderPane({uid,locked,onChanged}:{uid:number;locked:boolean;onChanged:()=>void}){
 const [state,setState]=useState<ProviderStatus|null>(null),[source,setSource]=useState<'server'|'byok'>('server'),[endpoint,setEndpoint]=useState('https://api.deepseek.com'),[model,setModel]=useState('deepseek-v4-flash-vision-exp'),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const active=useRef<AbortController|null>(null),alive=useRef(true)
 const request=async(method='GET',body?:unknown)=>{active.current?.abort();const controller=new AbortController();active.current=controller
  const timer=setTimeout(()=>controller.abort(),35000)
  try{const response=await fetch('/api/agent/provider'+(method==='POST'?'/connect':''),{method,credentials:'same-origin',signal:controller.signal,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(controller.signal.aborted||!alive.current)return null;if(response.headers.get('X-Agent-Owner')!==String(uid))throw new Error('身份已变化，请重新打开助手。');if(!response.ok)throw new Error(data.error??'连接失败');return data as ProviderStatus}finally{clearTimeout(timer)}}
 useEffect(()=>{alive.current=true;void request().then(data=>{if(data){setState(data);setSource(data.source);if(data.endpoint)setEndpoint(data.endpoint);if(data.model)setModel(data.model)}}).catch(e=>{if(alive.current)setError(e instanceof Error?e.message:'连接失败')});return()=>{alive.current=false;active.current?.abort()}},[uid])
 const connect=async()=>{if(locked||busy)return;setBusy(true);setError('');const credential=key;setKey('')
  try{const data=await request('POST',source==='server'?{source}:{source,endpoint,model,key:credential});if(data){setState(data);onChanged()}}catch(e){if(alive.current){setError(e instanceof Error?e.message:'连接失败');onChanged()}}finally{if(alive.current)setBusy(false)}}
 return <div className="agent-pane agent-scroll"><div className="agent-segments"><button type="button" className={source==='server'?'on':''} disabled={locked||busy} onClick={()=>setSource('server')}>项目服务器 AI</button><button type="button" className={source==='byok'?'on':''} disabled={locked||busy} onClick={()=>setSource('byok')}>自配 API</button></div>
  {source==='byok'&&<><div className="agent-suggestions">{state?.profiles.map(p=><button type="button" key={p.endpoint+p.model} disabled={locked||busy} onClick={()=>{setEndpoint(p.endpoint);setModel(p.model)}}>{p.model} · {p.contextTokens/1000}k</button>)}</div><label className="agent-field">Endpoint<input value={endpoint} maxLength={300} disabled={locked||busy} onChange={e=>setEndpoint(e.target.value)}/></label><label className="agent-field">模型<input value={model} maxLength={100} disabled={locked||busy} onChange={e=>setModel(e.target.value)}/></label><label className="agent-field">API Key<input type="password" autoComplete="off" value={key} maxLength={4096} disabled={locked||busy} onChange={e=>setKey(e.target.value)}/></label><p className="agent-pane-hint">连接检查会产生少量 API 费用；不会自动切换模型。</p></>}
  <button type="button" className="btn btn-primary btn-sm" disabled={locked||busy||!state||state.disabled||(source==='server'?!state.enabled:!key.trim())} onClick={()=>void connect()}>{busy?'连接中…':state?.ready&&state.source===source?'重新连接':'连接 AI'}</button>
  <p role="status" className="agent-pane-hint">{error||(!state?.enabled?'服务器 AI 尚未启用':state.ready?`已连接 · ${state.source==='server'?'项目 AI':'自配 API'} · ${state.model}`:state.canPrepare?'已配置':'尚未连接')}</p>
  {state?.usage&&<p className="agent-pane-hint">今日 {state.usage.turns} 轮 · {state.usage.tokens} token · 估算 US${state.usage.cost.toFixed(4)}</p>}
 </div>
}
